### ISSUE TITLE
client keeps saying "CLI is updating"

### ISSUE THREAD

**Issue by diwu1989** [heroku/heroku#1552]
I'm on linux, have heroku upgraded to the latest version, but everytime I run heroku, the warning CLI is updating appears.

```
WARNING: CLI is updating
heroku-toolbelt/3.36.4 (x86_64-linux) ruby/1.9.3
WARNING: CLI is updating
heroku-cli/4.19.5-f1ed6e0 (amd64-linux) go1.4.2
WARNING: CLI is updating
=== Installed Plugins
heroku-repo
heroku-vim
papertrail-heroku-plugin

**Comment by dickeyxxx** [comment]
hmm I think something is stuck, try deleting `~/.heroku/heroku-cli`

**Comment by diwu1989** [comment]
fixed, I see the following files:
```
autoupdate       heroku-cli.new         node_modules   usage
autoupdate.last  heroku-cli.old         plugins
error.log        iojs-v2.0.0-linux-x64  updating.lock
```
which ones should also be removed?

**Comment by dickeyxxx** [comment]
oh remove that `updating.lock` file

**Comment by diwu1989** [comment]
Done, thanks, is it possible for you guys to write some cleanup logic into the upgrade process?

**Comment by dickeyxxx** [comment]
yeah it should check to see if the updating file is still valid

**Comment by Taytay** [comment]
I just ran into this as well. All I see is: 
```
$ heroku help
WARNING: CLI is updating
```
And it hangs. Removing updating.lock allowed it to work.

**Comment by dickeyxxx** [comment]
I recently removed that warning, though it shouldn't have made it hang. I don't think it was actually hanging, I think it was installing iojs.

**Comment by Taytay** [comment]
Oh weird. My download/upload monitor showed nothing happening for many
minutes. I didn't check my activity monitor. As soon as I removed that file
and re-ran the app, I saw it download/uploading, and then it eventually
finished updating...

**Comment by dickeyxxx** [comment]
odd. Last week the updater ran synchronously, so that might've caused it to block while updating, but now there is a 2-stage updater that will only block for updates if it hasn't updated in over a week. Otherwise it will fork off an update task in the background after running a command. You use it often enough you will probably never see it block for updates. Also, when that updates happens, it tells you what it is doing.

This is all for the v4 updates btw, the v3 ones still update with that `updating... updated to v3.xx.x` text.

The only thing that downloads/installs in the background in the latest version is the iojs install, which I figured might be a bit verbose information. It should be pretty fast too. If you start seeing this again, could you try running it with `HEROKU_DEBUG=true`? That will print out information about downloading/installing iojs.

Apologies for the general flakiness around this stuff. When I moved the heroku git commands over to the new v4 stuff we got our first big chunk of people testing it and it helped iron out some of the issues with the autoupdater and setup. I think pretty much everything is solid now.

**Comment by dickeyxxx** [comment]
@Taytay are you in Europe by chance? I'm curious how quickly iojs installs there. You could roughly find out by deleting it: `rm -rf ~/.heroku/iojs-v*` and running `time heroku version`.

All of the other parts of the new CLI update via cloudfront, so it should be as fast there as it is here.

**Comment by Taytay** [comment]
I'm actually in South America at the moment, so I'm afraid I can't help. I can in 3 weeks or so though. If any of our European friends stumble across this in the meantime, perhaps they can give that a shot.

**Comment by dickeyxxx** [comment]
South America is just as good! I want to know what it's like outside North America.
