### ISSUE TITLE
Error when promoting a DB: `DATABASE on foo is the last billing attachment to sailing-keenly-4016;`

### ISSUE THREAD

**Issue by Taytay** [heroku/heroku#1562]
I haven't seen if this is repeatable or not, but we just got this when upgrading a DB on a newly forked app, and we weren't getting this before.
```
00:26:23.896 + heroku pg:promote YELLOW --app our_app
00:26:24.809 Promoting thinking-gently-8360 to DATABASE_URL on our_app... failed
00:26:24.810  !    DATABASE on our_app is the last billing attachment to sailing-keenly-4016; either remove the add-on entirely or add a new attachment to it before replacing its config vars.
```

**Comment by dickeyxxx** [comment]
@uhoh-itsmaciek do you know what this error means?

**Comment by bjeanes** [comment]
The error message should be improved but essentially it's indicating that promoting over the existing database which occupies the `DATABASE` alias (`sailing-keenly-4016`) would orphan it. You need to either give it a second alias (with `heroku addons:attach sailing-keenly-4016`) before promoting over the current alias or deprovision it entirely.

#1557 is designed to do this for you automatically but hasn't landed yet.

**Comment by bjeanes** [comment]
@Taytay oh and the reason this is new is because we're removing the special "create two names" behaviour that *only* Heroku Postgres has. Previously, the first HPG instance installed on an app got both a colour-based name and the `DATABASE` name. Now it just gets the latter (if available). #1557 is designed to rename the existing `DATABASE` on promotions so that the error message you are seeing isn't shown here.
