### ISSUE TITLE
undefined method `resource_name' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by noortotah** [heroku/heroku#1837]
while trying to upgrade heroku database from hobby-dev to hobby-basic, I get the following error

     Error:       undefined method `resource_name' for nil:NilClass (NoMethodError)
     Command:     heroku pg:copy .....
     Error ID:    7249e244738d4012924e8272ea340a78

**Comment by ransombriggs** [comment]
@noortotah Sorry for the delayed response.  Are you calling pg:copy with both SOURCE and TARGET using the format postgres:// ?  Also, what is your app name?  (available from `heroku apps:info`)  I can take a look at your setup and try and give you a solution, because I think I can see the bug right now and this extra info will help me confirm.

**Comment by noortotah** [comment]
@ransombriggs Thank You :) ,, the problem was I used the full url of the database instead of using the colors ,,

**Comment by frederick036** [comment]
@noortotah I have the exact same problem using the Postgres database when I tried to upgrade. What do you mean by "colors"?

**Comment by ransombriggs** [comment]
@frederick036 The colors refers to the config vars that are used for attached databases like `HEROKU_POSTGRESQL_WHITE`.  If you use config vars to specify one the heroku database urls, then the copy should work.

**Comment by frederick036** [comment]
@ransombriggs Thanks, it works!
