### ISSUE TITLE
heroku local:run should support --exit-code passthrough

### ISSUE THREAD

**Issue by evictor** [heroku/heroku#1856]
By extension of this: https://github.com/heroku/heroku/issues/186

**Comment by dadicool** [comment]
+1

**Comment by ransombriggs** [comment]
@evictor Right now the exit code from the command is passed back without the `--exit-code` flag.  Are you wanting this for consistency, where the command would accept the flag but do nothing different?  Or is there something else you expect to happen?
```
-> % heroku local:run python -c "exit(2)"
[WARN] No ENV file found
rbriggs@ebriggs-ltm [11:14:14] [~/src/github.com/heroku/heroku-local] [master]
-> % echo $?
2
rbriggs@ebriggs-ltm [11:14:16]
```

**Comment by ransombriggs** [comment]
@evictor Did not notice that your request was fairly old, the command has changed since then and it should be exiting with the proper code now.

@evictor Could you make sure you have `heroku-local@5.0.1` using `heroku version` and then check to see if the exit code you see from `heroku local:run` matches what you expect?  If you are not up to date, you can run `heroku update` to bring everything up to date.

**Comment by evictor** [comment]
Yes, I believe it is fixed now. Thanks!
