### ISSUE TITLE
processes doesn't pass through exit codes

### ISSUE THREAD

**Issue by choxi** [heroku/heroku#186]
It doesn't seem like `heroku run` passes back the exit code:

````
% heroku run "jflsda"
Running jfdlksa attached to terminal... up, run.34
sh: jfdlksa: not found
% echo $?
0
````

Is there any way this could be added?

**Comment by samueltb** [comment]
+1

**Comment by JacobEvelyn** [comment]
@dickeyxxx any updates on this? Is there a reason incorporating the approach in https://github.com/glenngillen/heroku-exit-status isn't desirable?

**Comment by dickeyxxx** [comment]
are you having good luck with it @JacobEvelyn? I could look into adding it, it's a risky change simply because I don't have a great idea how it might possibly mess up people's flows, but I'm down to try it. I would love to solve this bug.

**Comment by niallsmart** [comment]
How about at least adding it as an opt-in command line parameter to `heroku run` (and then flipping it to the default in the next major bump)

**Comment by dickeyxxx** [comment]
how is that different than testing by installing the plugin?

**Comment by niallsmart** [comment]
@dickeyxxx my thinking being that if reticence to make a breaking-change is holding this up then putting it behind a command line flag solves for that. it would be nice if this was a supported part of the toolbelt instead of having to install a plugin.

**Comment by dickeyxxx** [comment]
@niallsmart you've got the right idea. The issue here is that discoverability in a CLI is tough, so not that many people would notice the flag. Also, the complex setups where people are potentially using run in  weird ways which may break their workflow are probably using it in scripts. The plugin is fine for testing the functionality works in a normal case, I'm worried about potential corner cases that I haven't yet considered.

In any case, this is worth pursuing and I think that corner cases will be few if any. I also think this will fix enough problems that we could work through whatever those corner cases are. I'm considering doing this next week, but if issues crop up I may have to revert.

**Comment by dickeyxxx** [comment]
I'm also of the opinion that the status code should just be the status code that was returned by the process, I don't think a flag is a good long-term solution.

**Comment by jekuno** [comment]
+1

**Comment by dickeyxxx** [comment]
good news (finally)! the new CLI will handle this problem, and I have a PR in to start testing it: https://github.com/heroku/heroku/pull/1519

Right now it will work behind a flag, but I intend to make that temporary if possible. There is a bit of work left to be done in the v4 module that works with this: https://github.com/heroku/heroku-run

Namely handling things like stdin and piping, but I hope to merge it soon.

**Comment by dickeyxxx** [comment]
this is out!

**Comment by geemus** [comment]
Awesome. :clap:

**Comment by stof** [comment]
@dickeyxxx the ``--exit-code`` option does not appear when running ``heroku help run``. this makes it very hard to discover it.

**Comment by dickeyxxx** [comment]
@stof thanks for pointing that out
https://github.com/heroku/heroku/pull/1546

**Comment by Taytay** [comment]
:+1: 
Thank you, thank you, thank you for this!
