### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Ahmed-Badawy** [heroku/heroku#1939]
Hello! I keep having this error. first time to use ur services. 
i'm tring to create upload nodejs app to ur server. my machine: windows 10 using heroku toolbelt
Issue:-

C:\Users\(username)\Downloads\Heroku [master]>    heroku login
heroku-cli: Installing Toolbelt v4... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       getaddrinfo: No such host is known.  (SocketError) (Excon::Errors::SocketError)
    Command:     heroku login
    Version:     heroku/toolbelt/3.42.45 (i386-mingw32) ruby/2.1.7
    Error ID:    c47aaf8f037042beb25fdceb46cfe78f

    More information in C:/Users/courtaks/.heroku/error.log

**Comment by ransombriggs** [comment]
@Ahmed-Badawy Could you please try again, that is usually a temporary DNS issue.

**Comment by Ahmed-Badawy** [comment]
thanks! it's working now. 
temporary DNS issue as you said. 

please try to figure this problem. it leaves users with very bad first impression. 
i'm closing this issue as it's solved.

**Comment by bhaider7** [comment]
Almost 6 months later, I got the exact same issue on the first interaction with heroku, not a good start.

I am behind a corporate firewall and git + npm are working perfectly fine (after one time proxy configuration).

The issue resolved automatically after sometime after initial frustration (and time consumption). Just shared my experience for any next user landing here until the issue is actually resolved.
