### ISSUE TITLE
help me out 

### ISSUE THREAD

**Issue by vikrantgithub** [heroku/heroku#2019]
[error.txt](https://github.com/heroku/heroku/files/501986/error.txt)

**Comment by ransombriggs** [comment]
@vikrantgithub you should submit a ticket at https://support.heroku.com/ so that it can be sent to the proper team to help you with your `git push` issue.  This repository is for issues with the CLI only, and if you submit to support they can forward your ticket to a team that will be able to better help you.

**Comment by vikrantgithub** [comment]
@ransombriggs  thank you
