### ISSUE TITLE
23.21.149.112 safe IP?

### ISSUE THREAD

**Issue by colt05-usr** [heroku/heroku#2027]
Hello!
I also had error #2014 and I set the ip for api.heroku.com to 23.21.149.112 in /etc/hosts. Is this a safe IP?
EDIT: I have to find the IP for each heroku domain to use or else it comes up with errors like `Could not resolve host: git.heroku.com`
Thanks.

**Comment by ransombriggs** [comment]
@colt05-usr heroku is impacted by the large scale dns outage today.  More information can be found [here](https://status.heroku.com/incidents/965) which includes a list of IP addresses to use until the outtage is over.  If you are not able to reach that site due to the DNS outtage, I am including the list here as well.

```
151.101.45.6    status.heroku.com
54.225.188.133  api.heroku.com
50.16.189.161   help.heroku.com id.heroku.com dashboard.heroku.com devcenter.heroku.com blog.heroku.com
50.19.103.36    rendezvous.runtime.heroku.com
107.21.99.123   ssl-doctor.heroku.com
174.129.22.147  git.heroku.com
50.19.85.156    heroku.com
```

**Comment by ransombriggs** [comment]
@colt05-usr the platform issue has been resolved, could you try removing the entries from `/etc/hosts` and trying again?

**Comment by colt05-usr** [comment]
I can do `heroku login` now, thanks!
